# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
apps/api/openapi/openapi.yaml:
  operation-4xx-response:
    - '#/paths/~1api~1v1~1status/get/responses'
    - '#/paths/~1api~1v1~1session/get/responses'
    - '#/paths/~1api~1v1~1session/delete/responses'
